"""
Milestone 5 — Grounded generation.

Pipeline stage implemented here (see the Architecture diagram in planning.md):

    5. Generation — take a user question, retrieve the top-k chunks (Milestone 4),
                    and ask the LLM to answer *using only those chunks*, then return
                    the answer together with a programmatically-built source list.

Grounding is enforced by construction, not merely requested:

  (a) RETRIEVAL GATE — if retrieval finds nothing above MIN_SCORE, we return the
      refusal string WITHOUT calling the LLM at all. An out-of-scope question can
      never reach the model, so it cannot be answered from the model's own
      knowledge.
  (b) CONTEXT-ONLY INPUT — the model is given ONLY the retrieved passages. It has
      no other documents to draw on.
  (c) HARD SYSTEM PROMPT — the model is instructed to use only the passages, to
      refuse with an EXACT sentinel string when they are insufficient, and to not
      use outside knowledge. temperature=0 makes this deterministic.
  (d) CODE-BUILT ATTRIBUTION — the `sources` returned to the caller are assembled
      in Python from the retrieved chunks' metadata (source label + url + doc_id).
      They are NOT parsed from, or generated by, the model. The model literally
      cannot omit, alter, or fabricate a source in the returned source list.

Usage:
    pip install -r requirements.txt          # groq, python-dotenv (+ gradio for app.py)
    cp .env.example .env                     # then put your real GROQ_API_KEY in .env
    python retrieval.py build                # index must exist first
    python generate.py "how is the food at commons?"
"""

from __future__ import annotations

import os
import re
import sys

import retrieval

# ----------------------------------------------------------------------------
# Spec / knobs
# ----------------------------------------------------------------------------
GEN_MODEL = "llama-3.3-70b-versatile"   # Groq-hosted; requirements.txt pins `groq`
DEFAULT_TOP_K = retrieval.DEFAULT_TOP_K  # 5, from planning.md

# Retrieval gate: if the best chunk's cosine similarity is below this, we treat
# the question as out of scope and refuse WITHOUT calling the LLM. Tunable — on
# this corpus/model, on-topic hits score ~0.6+ and clearly off-topic ones fall
# well below (see the score discussion in the README). Kept conservative so we
# don't wrongly refuse borderline-but-valid dining questions.
MIN_SCORE = 0.35

# The single, exact refusal string. Both the gate (code) and the system prompt
# (model) use THIS string, so a refusal looks identical no matter which path
# produced it, and the interface can detect it to suppress the source list.
REFUSAL = "I don't have enough information in my sources to answer that."

# ----------------------------------------------------------------------------
# The system prompt enforces grounding. Note it does not "suggest" using the
# context — it forbids everything else and pins an exact refusal string.
# ----------------------------------------------------------------------------
SYSTEM_PROMPT = f"""You answer questions about the RPI (Rensselaer Polytechnic Institute) campus dining experience.

You will be given a numbered list of context passages retrieved from a document collection. Follow these rules exactly:

1. Answer ONLY using information stated in the provided context passages. Treat those passages as your only source of truth.
2. Do NOT use any prior or outside knowledge, and do NOT guess, infer, or fill gaps — even if you are confident you know the answer.
3. If the passages do not contain enough information to answer the question, reply with EXACTLY this sentence and nothing else:
{REFUSAL}
4. If only part of the question is supported by the passages, answer only that part and state what the passages do not cover.
5. In your answer, NAME the source document each fact came from, using the exact source names shown in the context above — for example: "According to the Reddit Post (hows the food), ..." or "(University Magazine — food for thought)". Every factual claim must name the document it came from.
6. Be concise and stay strictly within what the passages say. Do not add commentary, disclaimers, or invented details."""


# ----------------------------------------------------------------------------
# Context + source assembly (both derived from the SAME retrieval results)
# ----------------------------------------------------------------------------
def _source_name(r: dict) -> str:
    """
    A human-readable, reasonably unique name for the document a chunk came from,
    used both in the context (so the model can cite it) and in the source list.

    Combines the source label with a prettified document id, because labels alone
    repeat (e.g. three different documents are all "Reddit Post"). Example:
    doc_id "07_hows_the_food" + source "Reddit Post" -> "Reddit Post (hows the food)".
    """
    label = (r.get("source") or "").strip()
    doc = r.get("doc_id") or ""
    pretty = re.sub(r"^\d+_", "", doc).replace("_", " ").strip()
    if label and pretty:
        return f"{label} ({pretty})"
    return label or pretty or "unknown source"


def _format_context(results: list[dict]) -> str:
    """Render retrieved chunks as a numbered list the model must answer from.

    Each passage is headed with its citable source NAME so the model can name
    the document in its answer (system prompt rule 5).
    """
    blocks = []
    for r in results:
        blocks.append(f"[{r['rank']}] Source: {_source_name(r)}\n{r['text']}")
    return "\n\n".join(blocks)


def _build_sources(results: list[dict]) -> list[dict]:
    """
    Build the authoritative source list from retrieval METADATA, in Python.

    This is the guarantee the spec asks for: attribution is derived from the
    chunks that were actually retrieved and placed in context, deduplicated by
    document, preserving best (lowest) rank order. The LLM is never consulted to
    produce this list, so it cannot be dropped or fabricated by the model.
    """
    seen: dict[str, dict] = {}
    for r in results:
        doc_id = r.get("doc_id", "")
        if doc_id not in seen:
            seen[doc_id] = {
                "doc_id": doc_id,
                "source": r.get("source", ""),
                "name": _source_name(r),          # same citable name the model sees
                "url": r.get("url", ""),
                "best_rank": r["rank"],
                "best_score": round(r["score"], 3),
            }
    return list(seen.values())


# ----------------------------------------------------------------------------
# LLM call
# ----------------------------------------------------------------------------
def _call_llm(question: str, context: str) -> str:
    """Send the grounded prompt to Groq. temperature=0 for determinism."""
    try:
        from groq import Groq
    except ImportError:
        sys.exit("groq is required: pip install -r requirements.txt")

    try:
        from dotenv import load_dotenv
        load_dotenv()  # read GROQ_API_KEY from .env (never committed)
    except ImportError:
        pass  # dotenv optional if the env var is already set another way

    api_key = os.environ.get("GROQ_API_KEY")
    if not api_key or api_key == "your_key_here":
        sys.exit("GROQ_API_KEY is not set. Copy .env.example to .env and add your key.")

    user_message = (
        f"Question: {question}\n\n"
        f"Context passages:\n{context}\n\n"
        "Answer the question using only the passages above."
    )

    client = Groq(api_key=api_key)
    response = client.chat.completions.create(
        model=GEN_MODEL,
        temperature=0,                      # deterministic; no creative drift
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": user_message},
        ],
    )
    return response.choices[0].message.content.strip()


# ----------------------------------------------------------------------------
# Public entry point
# ----------------------------------------------------------------------------
def generate_answer(question: str, top_k: int = DEFAULT_TOP_K, max_per_source: int | None = None) -> dict:
    """
    Retrieve, then generate a grounded answer.

    Returns a dict:
      {
        "answer":   str,          # the model's answer, or the exact REFUSAL string
        "grounded": bool,         # False when we refused (gate or model refusal)
        "sources":  list[dict],   # code-built attribution (empty on refusal)
        "contexts": list[dict],   # the chunks that were placed in context
      }
    """
    results = retrieval.retrieve(question, top_k=top_k, max_per_source=max_per_source)

    # (a) Retrieval gate — refuse before the LLM is ever called if nothing is
    #     relevant enough. No sources are attributed to a refusal.
    if not results or results[0]["score"] < MIN_SCORE:
        return {"answer": REFUSAL, "grounded": False, "sources": [], "contexts": []}

    context = _format_context(results)
    answer = _call_llm(question, context)

    # If the model itself refused, don't attach sources (nothing was used).
    grounded = answer.strip() != REFUSAL
    sources = _build_sources(results) if grounded else []

    return {"answer": answer, "grounded": grounded, "sources": sources, "contexts": results}


# ----------------------------------------------------------------------------
def _print(result: dict) -> None:
    print("\n" + "=" * 70)
    print(result["answer"])
    if result["sources"]:
        print("\nSources:")
        for i, s in enumerate(result["sources"], start=1):
            line = f"  {i}. {s.get('name') or s['source']}"
            if s["url"]:
                line += f" — {s['url']}"
            print(line)
    print("=" * 70)


def main() -> None:
    import argparse

    parser = argparse.ArgumentParser(description="Grounded generation over the RPI dining corpus (Milestone 5).")
    parser.add_argument("question", help="the question to answer")
    parser.add_argument("--top-k", type=int, default=DEFAULT_TOP_K)
    parser.add_argument("--max-per-source", type=int, default=None)
    args = parser.parse_args()

    result = generate_answer(args.question, top_k=args.top_k, max_per_source=args.max_per_source)
    _print(result)


if __name__ == "__main__":
    main()
